<?php $__env->startSection('content'); ?>
<div class="container-fluid mt--6">
  <div class="content-wrapper">
    <div class="row">
      <div class="col-md-12">    
        <div class="card">
          <div class="card-header checkx">
            <h3 class="mb-0 text-dark"><?php echo e(__('Two-Factor Security Option')); ?></h3>
          </div>
          <div class="card-body">
            <div class="align-item-sm-center flex-sm-nowrap text-left">
                <p class="text-sm text-dark">
                <?php echo e(__('Two-factor authentication is a method for protection your web account. 
                  When it is activated you need to enter not only your password, but also a special code. 
                  You can receive this code by in mobile app. 
                  Even if third person will find your password, then cant access with that code.')); ?>

                </p>
                <span class="badge badge-pill badge-primary mb-3">
                  <?php if($user->fa_status==0): ?>
                  <?php echo e(__('Disabled')); ?>

                  <?php else: ?>
                  <?php echo e(__('Active')); ?>

                  <?php endif; ?>
                </span>
                <ul class="text-default text-sm">
                  <li><?php echo e(__('Install an authentication app on your device. Any app that supports the Time-based One-Time Password (TOTP) protocol should work.')); ?></li>
                  <li><?php echo e(__('Use the authenticator app to scan the barcode below.')); ?></li>
                  <li><?php echo e(__('Enter the code generated by the authenticator app.')); ?></li>
                </ul>
                <a data-toggle="modal" data-target="#modal-form2fa" href="" class="btn btn-success btn-sm">
                <?php if($user->fa_status==0): ?>
                  <?php echo e(__('Enable 2fa')); ?>

                <?php elseif($user->fa_status==1): ?>
                  <?php echo e(__('Disable 2fa')); ?>

                <?php endif; ?>
                </a>
                <div class="modal fade" id="modal-form2fa" tabindex="-1" role="dialog" aria-labelledby="modal-form" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered" role="document">
                      <div class="modal-content form-block form-modal">
                        <div class="modal-body text-center">
                          <?php if($user->fa_status==0): ?>
                            <img src="<?php echo e($image); ?>" class="mb-3 user-profile">
                          <?php endif; ?>
                          <form action="<?php echo e(route('change.2fa')); ?>" method="post">
                            <?php echo csrf_field(); ?>
                            <div class="form-group row">
                              <div class="col-lg-12">
                                <input type="text" pattern="\d*" name="code" class="form-control" minlength="6" maxlength="6" placeholder="Six digit code" required>
                                  <input type="hidden"  name="vv" value="<?php echo e($secret); ?>">
                                <?php if($user->fa_status==0): ?>
                                  <input type="hidden"  name="type" value="1">
                                <?php elseif($user->fa_status==1): ?>
                                  <input type="hidden"  name="type" value="0">
                                <?php endif; ?>
                              </div>
                            </div>            
                            <div class="text-right">
                              <button type="submit" class="btn btn-neutral btn-block">
                              <?php if($user->fa_status==0): ?>
                                <?php echo e(__('Enable 2fa')); ?>

                              <?php elseif($user->fa_status==1): ?>
                                <?php echo e(__('Disable 2fa')); ?>

                              <?php endif; ?>
                              </button>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
<?php $__env->stopSection(); ?>
<?php echo $__env->make('userlayout', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /Applications/XAMPP/xamppfiles/htdocs/flutter/core/resources/views/user/security/2fa.blade.php ENDPATH**/ ?>